### ISSUE TITLE
Current version (0.99) doesn't match installed version

### ISSUE THREAD

**Issue by legacy-code** [atmb4u/dodo#9]
The latest version (0.99) in the repo is not the same version that is installed as through the instructions (pip install dodopie) -- it actually installs 0.98.

This isn't really a problem (if you already have a DODO file), except that from 0.98 to 0.99, the choice parameter was added in the ArgumentParser.
## 0.98

```
312:      parser.add_argument("operation", type=str,
313:                        help="List all existing dodos add, propose, accept, reject, workon, finish, remove")
```
## 0.99

```
324:      parser.add_argument("operation", nargs='?', default=default_operation,
325:                          choices=[
326:                              'accept',
327:                              'add',
328:                              'finish',
329:                              'flush',
330:                              'list',
331:                              'propose',
332:                              'reject',
333:                              'remove',
334:                              'workon'
335:                          ],
336:                          help="The operation to perform")
```

when version 0.99 is run **'dodo init'**, you get the following error:

```
usage: dodo.py [-h] [-d DESC] [-u USER] [-t TIME] [--id ID] [-f FILE]
               [-i INPUT] [-o OUTPUT]
               [{accept,add,finish,flush,list,propose,reject,remove,workon}]
               [quick_access]
dodo.py: error: argument operation: invalid choice: 'init' (choose from 'accept', 'add', 'finish', 'flush', 'list', 'propose', 'reject', 'remove', 'workon')
```

You do NOT fall through to the code below, but the ArgumentParser() throws an exception (as above) with a message on line 348.

It's easily fixed by adding 'init' to the choices for "operation".  

Took me a minute to figure out what was going.

I looked but didn't see where this change was introduced, but stumbled on it when I wanted to play with the script from the repo (just copied it from the master branch).

Anyway, just wanted to let you know.

**Comment by legacy-code** [comment]
the choices should also include:  import, export, c, and d

otherwise, it will do the same as above

**Comment by atmb4u** [comment]
Thank you very much for the bug report. I've fixed those bugs and updated it on the pypi to dodopie 1.1.  😃 
Your effort is much appreciated, and I've included your name into the contributor list.
Thank you again. 👏
